# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.${DOMAIN_NAME}.com:
    container_name: orderer.${DOMAIN_NAME}.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/${DOMAIN_NAME}.com/orderers/orderer.${DOMAIN_NAME}.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/${DOMAIN_NAME}.com/orderers/orderer.${DOMAIN_NAME}.com/tls/:/var/hyperledger/orderer/tls
        - orderer.${DOMAIN_NAME}.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.${ORG1_NAME}.${DOMAIN_NAME}.com:
    container_name: peer0.${ORG1_NAME}.${DOMAIN_NAME}.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.${ORG1_NAME}.${DOMAIN_NAME}.com
      - CORE_PEER_ADDRESS=peer0.${ORG1_NAME}.${DOMAIN_NAME}.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.${ORG1_NAME}.${DOMAIN_NAME}.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.${ORG1_NAME}.${DOMAIN_NAME}.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.${ORG1_NAME}.${DOMAIN_NAME}.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/${ORG1_NAME}.${DOMAIN_NAME}.com/peers/peer0.${ORG1_NAME}.${DOMAIN_NAME}.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/${ORG1_NAME}.${DOMAIN_NAME}.com/peers/peer0.${ORG1_NAME}.${DOMAIN_NAME}.com/tls:/etc/hyperledger/fabric/tls
        - peer0.${ORG1_NAME}.${DOMAIN_NAME}.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.${ORG1_NAME}.${DOMAIN_NAME}.com:
    container_name: peer1.${ORG1_NAME}.${DOMAIN_NAME}.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.${ORG1_NAME}.${DOMAIN_NAME}.com
      - CORE_PEER_ADDRESS=peer1.${ORG1_NAME}.${DOMAIN_NAME}.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.${ORG1_NAME}.${DOMAIN_NAME}.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.${ORG1_NAME}.${DOMAIN_NAME}.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.${ORG1_NAME}.${DOMAIN_NAME}.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/${ORG1_NAME}.${DOMAIN_NAME}.com/peers/peer1.${ORG1_NAME}.${DOMAIN_NAME}.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/${ORG1_NAME}.${DOMAIN_NAME}.com/peers/peer1.${ORG1_NAME}.${DOMAIN_NAME}.com/tls:/etc/hyperledger/fabric/tls
        - peer1.${ORG1_NAME}.${DOMAIN_NAME}.com:/var/hyperledger/production

    ports:
      - 8051:8051

  peer0.${ORG2_NAME}.${DOMAIN_NAME}.com:
    container_name: peer0.${ORG2_NAME}.${DOMAIN_NAME}.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.${ORG2_NAME}.${DOMAIN_NAME}.com
      - CORE_PEER_ADDRESS=peer0.${ORG2_NAME}.${DOMAIN_NAME}.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.${ORG2_NAME}.${DOMAIN_NAME}.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.${ORG2_NAME}.${DOMAIN_NAME}.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.${ORG2_NAME}.${DOMAIN_NAME}.com:10051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/${ORG2_NAME}.${DOMAIN_NAME}.com/peers/peer0.${ORG2_NAME}.${DOMAIN_NAME}.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/${ORG2_NAME}.${DOMAIN_NAME}.com/peers/peer0.${ORG2_NAME}.${DOMAIN_NAME}.com/tls:/etc/hyperledger/fabric/tls
        - peer0.${ORG2_NAME}.${DOMAIN_NAME}.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.${ORG2_NAME}.${DOMAIN_NAME}.com:
    container_name: peer1.${ORG2_NAME}.${DOMAIN_NAME}.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.${ORG2_NAME}.${DOMAIN_NAME}.com
      - CORE_PEER_ADDRESS=peer1.${ORG2_NAME}.${DOMAIN_NAME}.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.${ORG2_NAME}.${DOMAIN_NAME}.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.${ORG2_NAME}.${DOMAIN_NAME}.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.${ORG2_NAME}.${DOMAIN_NAME}.com:9051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/${ORG2_NAME}.${DOMAIN_NAME}.com/peers/peer1.${ORG2_NAME}.${DOMAIN_NAME}.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/${ORG2_NAME}.${DOMAIN_NAME}.com/peers/peer1.${ORG2_NAME}.${DOMAIN_NAME}.com/tls:/etc/hyperledger/fabric/tls
        - peer1.${ORG2_NAME}.${DOMAIN_NAME}.com:/var/hyperledger/production
    ports:
      - 10051:10051
